name: Node.js CI (Testing)

defaults:
  run:
    working-directory: ./tests

on:
  push:
  workflow_dispatch:

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6
      - name: Use PNPM Package Manager
        uses: pnpm/action-setup@v6
        with:
          version: "11.13"
      - name: Install Dependencies
        run: pnpm install --frozen-lockfile
      - name: Test Package/Project
        run: pnpm tsx index.ts
