name: "[Static] Node.js CI (Fetch Resources)"

defaults:
  run:
    working-directory: ./scripts

on:
  schedule:
    - cron: "0 12 * * *"
  workflow_dispatch:

permissions:
  contents: write

jobs:
  check:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6
      - name: Use PNPM Package Manager
        uses: pnpm/action-setup@v6
        with:
          version: 11
      - name: Run scripts
        run: pnpm tsx fetchResources.ts
      - uses: EndBug/add-and-commit@v10
        with:
          add: '["packages/static/constants","packages/static/jsr.json"]'
          message: "Updated Constants"
          default_author: "github_actions"
